### ISSUE TITLE
OWASP Wiki - Secure Coding Dojo

### ISSUE THREAD

**Issue by CloudOnFleek** [trendmicro/SecureCodingDojo#16]
The description on the wiki starts with a sentence that needs clarification.

Description
While open source training sites to teach application security concepts are not new the target audience for these sites has been pen-testers and ethical hackers.

**Comment by paul-ion** [comment]
Thank you. I think that clarification was made in detail in the AppSec DC presentation. I prefer to keep the text of the wiki concise and I don't think that statement is necessary.
