### ISSUE TITLE
CWE22 - Path Traversal accetps a wrong answer

### ISSUE THREAD

**Issue by jose-raul-barreras** [trendmicro/SecureCodingDojo#25]
In CWE22 - Path Traversal, the attack `http://127.0.0.1:8080/cwe22.jsp?file=../cwe22.jsp` succeed, and shows [`cwe22.jsp`]'s content(https://github.com/trendmicro/SecureCodingDojo/blob/master/insecureinc/WebContent/cwe22.jsp)., because the answer "secret.password=12345678" is hardcoded.  
When you click on the "Get your code' button, it goes to 'http://127.0.0.1:8080/%s' and returns a 400 error:
```
HTTP Status 400 – Bad Request
Type Status Report

Message Invalid URI: EOF

Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).

Apache Tomcat/8.5.40
```
In the other hand, the answer proposed in `main#!/solution/cwe22`, `cwe22.jsp?file=../WEB-INF/web.xml`, does not work, returning a ERR_CONNECTION_RESET error. 
It works with `cwe22.jsp?file=../WEB-INF/config.properties`

**Comment by paul-ion** [comment]
Hi, this is not happening with the latest container image. Are you running it from Eclipse with a different Tomcat version perhaps? 

![image](https://user-images.githubusercontent.com/31246137/74233787-5a7bee00-4c99-11ea-97c5-bcc7c55bef75.png)

**Comment by jose-raul-barreras** [comment]
Hi Paul!
My bad. I'm not running the app in a local environment. The URL is http://10.100.160.79:8080/cwe22.jsp?file=../cwe22.jsp
![image](https://user-images.githubusercontent.com/10443833/74670389-b26d9580-516e-11ea-8a4a-1f23d93a8f8a.png)

I believe that I'm using the latest version: I cloned the repo and called docker-compose.

**Comment by nagelfargithub** [comment]
Just encountered the same issue. cwe22.jsp?file=../WEB-INF/web.xml, does not work and instead returns a ERR_CONNECTION_RESET error. It works with cwe22.jsp?file=../WEB-INF/config.properties but there is no way for me to find out the name of the properties file as I can not include the web.xml first.
